### Checked & Unchecked Exception in Java

```
    Normal flow:
    - Wake up -> Ready -> Bike/Car/Auto -> Office Work -> Office Off -> Sleep
    
    - exception occur: late wake up - whole normal flow is disturbed 
    - exception occur: Bike/Car/Auto problem - next normal flow is disturbed.
    - exception occur: Offie work not completed - next normal flow is disturbed.

  
    Compiler 
  +----------+
  |  Mother  |   
  +----------+
  - Mother can check the late wake up exception. Example, to check office/school id card, purse 
  - But Mother can not check the Bike/Car/Auto problem exception. Example, Accident
  
  - Checked Exception: Compilere can check
  - Unchecked Exception: Compilere can not check
  Note: Exception always comes at the Run time.
  
```

- Note:
    - Exception never occur at the compile time.
    - Exception always comes/occurs at the Run time.
    - How? Mother only check her kind of things/job only if the flow start, otherwise she will not check the things..
    - e.g. you are sleeping late on sunday then she does not check it. Because you are not going to the office/school so
      no need to check..

```java

// try to run this program: using the notepad because in IDE you can see red line...
// you will get the error:

class Test1 {
    public static void main(String[] args) {
        FileInputStream fis = new FileInputStream("e://aaa.txt");
    }
}

/*
  java: unreported exception java.io.FileNotFoundException; must be caught or declared to be thrown 
  
  What is the meaning of this above line?
  - It means in future it will give the exception.
  - So you need to report(handle) it. But how you can do it?
  - By using the throw keyword or using the try-catch.  
  - For compilation, we must have the throw keyword or try-catch. Otherwise, it will not be compile the program.     
 */

/*
        you can import the package manually by using this in the notepad
        import java.io.FileInputStream;
        import java.io.FileNotFoundException;
        import java.io.IOException;
 */
```

```java

// Program link: src/com/jayshah/chapter_7_Exception_Handling/_2_Checked_Unchecked_Exceptions_Throw/Test2.java

// Unchecked Exception

class Test2 {
    public static void main(String[] args) {
        int a = 100, b = 0, c;
        c = a / b;
        System.out.println(c);
    }
}

/*
    - For compile: javac Test2.java
    - For Run: java Test
    
    - Compile this program you can not see any error reported.
    - But at run time you will see the exception 
    
    - Exception in thread "main" java.lang.ArithmeticException: / by zero
    
 */

/*
    - Here in Unchecked Exception, we do not require the throw keyword or try-catch because compiler can be able to compile.    
 */
```

- Programs:
    - checkedexception/Test1.java
    - Demo/Test1.java
    - Demo/Voting.java
    - Test1.java
    - Test2.java

#### What is Checked and Unchecked Exception :-

1.
    - Checked exception is the exception which can be checked by the compiler.
    - Unchecked exception is the exception which compiler cannot check.


2.
    - If we do not report checked exception, our program will not compile.
    - In case of Unchecked exception, if we do not report the exception then our program can compile.


3.
    - In case of checked exception we have to use throws or try-catch keyword.
    - In case of unchecked exception its not compulsory to use throws or try-catch keyword.


4.
    - Parent class of checked exceptions are "`Exception`" class.
    - Parent class of unchecked exceptions are "RuntimeException" class.

- NOTE : Exceptions are always occur at runtime, no exception is occurred at compile time.

------------------------

```

This is 2 different area.
In area A, if crime happens then responnbility to handle those things
are in that particular sector of the police.
Similarly in area B, it has different sector of the police. 


        Area : A                    Area : B
        police                      police
        _______________             _______________
       |               |           |               |
       |  crime        |           | crime         |
       |               |           |               |
       |_______________|           |_______________|


Here in below example, ther is exception occured 
and responsbility to handle is the main() method.

class Test2 {
    public static void main(String[] args) {
        int a = 100, b = 0, c;
        c = a / b;
        System.out.println(c);
    }
}

But, here in this below example, responsbility to handle the exception is the 
    - ptioprity-1 : divide() method  (if not handle then)  
    - ptioprity-2 : m1() method  (if not handle then)  
    - ptioprity-3 : main() method  (if not handle then)  
    - still not handle then who call the main() method? i.e. JVM, 
    - Now, JVM knows nobody is handle this object(crime)
    - then JVM transfer this object to Default Exception Handler 
    - and JVM termionate main() method, 
        - main() method terminate m1(), 
        - m1() method terminate divide(). 

public class Test1 {
    public static void main(String[] args) {
        Test1 t1=new Test1();
        t1.m1();
    }
    void m1() {
        divide();
    }
    void divide() {
        int a=100, b=0, c;
        c=a/b;
        System.out.println(c);
    }
}

```
```
Here main() method has the exception so main() method creates one exception object

class Test2 {
    public static void main(String[] args) {
        int a = 100, b = 0, c;
        c = a / b;
        System.out.println(c);
    }
}

    main() method creates the Exception object
    and this object is the object of the ArithmeticException class's object.
    - in this object has total 3 things: Exception Class Name, Description (Message), Stack Trace (Location) 
    - Stack Trace (Location) : it has proper line number where exception is occurred.

    /-----------------------\
   /   Exception             \  --->  1.) Exception Class Name      
   \    Object               /  --->  2.) Description (Message)
    \-----------------------/   --->  3.) Stack Trace (Location) (Proper Line Number)
    
    - Now, it just creates the Exception object but nop body is handle it.
    - So, who execute the main() method? i.e. JVM.
    - Now, JVM sees main() method does not handle the Exception object.
    - Then, JVM do the program as abnormal terminate from that exception line
    - and transfer that exception object to Defalt-Exception-Handler. 
    - Defalt-Exception-Handler print that exception object. 

```



#### Working of exception :-

- If we do not handle the exception, out program will terminate abnormally (which is not good programming).
- If any exception is occurred in any method, then that method will create an exception object and that method has the responsibility to handle the exception.
- If the method is not handling the exception, then caller method has the responsibility to handle the exception.
- If any caller method is not handling the exception object then that object will be transferred to JVM and then Default Exception Handler.
- Then Default Exception Handler will print the exception object and JVM will terminate the exception object abnormally.

#### throw keyword :-
- throw keyword is used to create an exception object programmatically.
- Syntax :
  - `throw new ExceptionClassName();`
- throw keyword is mainly used for User-Defined Exceptions.



- by using the throw, programmer can create the exception object manually, same as what method creates.


- Note:
    - 1.) Who's responsible to create the exception object?
        - i.) method
        - ii.) programmer
            - if programmer wants to create the exception object, then it will be created by using the `throw` keyword.



#### How to handle the exceptions :-
- We can handle the exception by 2 ways :-

1. by using "throws" keyword
2. by using "try-catch" block



```java
public class Voting {
    public static void main(String[] args) {
        int age = 10;

        Voting v = new Voting();
        v.checkAge(age);
    }

    void checkAge(int age) {
        if (age >= 18) {
            youCanVote();
        } else {
            throw new RuntimeException("You cannot vote"); // manually create the exception object 
        }
    }

    void youCanVote() {
        System.out.println("you can vote successfully");
    }
}
```